---
#Install Elastic
- name: Install ElasticSearch.
  package:
    name: elasticsearch
    state: present

#Configure Elastic
- name: Copy template to /etc/elasticsearch/elasticsearch.yml
  template:
    src: elastic.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750

#Fix Java Config
- name: Check if -XX:+AssumeMP is on file
  shell: grep "-XX:+AssumeMP" /etc/elasticsearch/jvm.options | wc -l
  register: javaoptions
  ignore_errors: yes

- debug: msg="{{ javaoptions.stdout }}"

- name: Add -XX:+AssumeMP to /etc/elasticsearch/jvm.options
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    line: '-XX:+AssumeMP'
  when: javaoptions.stdout == "0" 

#Start and enable the service
- name: Start the service
  service:
    name: elasticsearch
    state: started
    enabled: true