---
#Install Kibana Dashboard
- name: Install Kibana
  package:
    name: kibana
    state: present

- name: Enable and start the Kibana Service
   service:
    name: kibana
    state: started
    enabled: true